# Generated by Django 3.1 on 2020-08-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps_data',
            name='data_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
