# Generated by Django 3.1 on 2021-01-28 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sayqac_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='dictionary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=20)),
                ('characteristic', models.CharField(max_length=20)),
                ('searched', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='generations',
            fields=[
                ('word', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('times', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='initiators',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('initiator', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='missing',
            fields=[
                ('word', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('times', models.IntegerField()),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.initiators')),
            ],
        ),
        migrations.CreateModel(
            name='parts_of_speach',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_of_speach', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='gps_data',
        ),
        migrations.DeleteModel(
            name='sayqac_data',
        ),
        migrations.AddField(
            model_name='generations',
            name='initiated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.initiators'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.parts_of_speach'),
        ),
    ]
